### ISSUE TITLE
Support multi-server DB?

### ISSUE THREAD

**Issue by EnziinSystem** [drecom/activerecord-turntable#82]
In fact, If we need sharding DB then we must multi-server host as below.
- Server MySQL 1: DB1-->DB100 (included user table)
- Server MySQL 2: DB101-->DB200
...
But I see database.yml config file with one only host DB.
```
    connection_spec: &spec
      adapter: mysql2
      encoding: utf8
      reconnect: false
      pool: 5
      username: root
      password: root
      socket: /tmp/mysql.sock
```
Please visit the link.

https://medium.com/@Pinterest_Engineering/sharding-pinterest-how-we-scaled-our-mysql-fleet-3f341e96ca6f

**Comment by gussan** [comment]
Yes, activerecord-turntable supports multi database hosts.
We can specify `host` variable as follows.

```yaml
connection_spec: &spec
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:

development:
  <<: *spec
  host: main_db
  database: sample_app_development
  seq:
    user_seq_1:
      <<: *spec
      host: sequence_db
      database: sample_app_user_seq_development
  shards:
    user_shard_1:
      <<: *spec
      host: user_db_1
      database: sample_app_user1_development
    user_shard_2:
      <<: *spec
      host: user_db_3
      database: sample_app_user2_development
    user_shard_3:
      <<: *spec
      host: user_db_3
      database: sample_app_user3_development
```

**Comment by gussan** [comment]
Yes, multi database hosts configuration is supported.
You can specify `host` properties as follows.

```yaml
connection_spec: &spec
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:

development:
  <<: *spec
  host: main_db
  database: sample_app_development
  seq:
    user_seq_1:
      <<: *spec
      host: sequence_db
      database: sample_app_user_seq_development
  shards:
    user_shard_1:
      <<: *spec
      host: user_db_1
      database: sample_app_user1_development
    user_shard_2:
      <<: *spec
      host: user_db_3
      database: sample_app_user2_development
    user_shard_3:
      <<: *spec
      host: user_db_3
      database: sample_app_user3_development
```
